### PR TITLE
Dice

### PR DESCRIPTION
**Pull request by L0neGamer**
Expression and dice parsing and evaluation

### CODE REVIEW

**Comment by L0neGamer** [comment]
Anna had a comment on the placement of Dice.hs on my original PR: <https://github.com/L0neGamer/tablebot/pull/1#discussion_r750105762>

**Comment by L0neGamer** [comment]
The parsers need to be modified, so suggestions for those would be useful

**Review by distributive — CHANGES_REQUESTED** [review]
- Could add `$r` as an alias for `$roll`
- Could add a default case (so `$roll` just rolls a d6)
- The rng error says "more than 150 dice" but also errors on exactly 150 (eg `$roll 150d6`)
- The error trace could filter out unnecessary brackets: `$roll ((((151d6))))`
- The error trace could be extended to show the position of the error inline (there's an ambiguous case in `$roll 100d6 + 100d6`)
- Personal thing: I'd call the negate function "neg" to line up with "abs"
- The fact function's limit-exception message doesn't state what the limit is
- `kh`/`hl`/`dh`/`dl`/etc all bold both the highest and lowest values in every case (is this intended?)
- Could add a not-equals condition (!= perhaps, I'm not sure what a one-character symbol for it could be)

**Comment by L0neGamer** [comment]
re: https://github.com/WarwickTabletop/tablebot/pull/54#pullrequestreview-821407574

completed most small things. better error trace (location) will need a fair amount of work. not-equals condition is gonna be tricky but should be feasible.

**Comment by L0neGamer** [comment]
This is an implementation of issue #2

**Pull request merged**
